import Head from 'next/head'
import Link from 'next/link'
import {sanityClient, urlFor} from '../lib/sanity'

const querySanity = `*[_type == 'recipe']{
  _id,
  name,
  slug,
  mainImage
}`

export async function getStaticProps(){

  const recipes = await sanityClient.fetch(querySanity)

  return {
    props:{
      recipes
    }
  }
}

export default function Home({recipes}) {

  return (
    <div>
      <Head>
        <title>Chemi's kitchen</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ul className='recipe-list'>
          {recipes?.length && recipes.map((recipe)=>(
            <li key={recipe._id} className="recipe-card">
              <Link href={`/recipes/${recipe.slug.current}`}>
                <a>
                  <img src={urlFor(recipe.mainImage).url()} alt={recipe.name}/>
                  <span>{recipe.name}</span>
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

